spring:
  data:
    mongodb:
      uri: mongodb://${db.host:localhost}:27017/samflix
      database: "samflix"
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /docs.html
    default-models-expand-depth: 0

logging:
  level:
    org.springframework.data.mongodb: debug
    web: debug